config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#index"
  get "static_pages/*page", to: "static_pages#show"

  get :admin, to: 'admin/dashboard#index'
  namespace :admin do
    resources :categories
    resources :words, only: [:create, :update, :destroy]
    resources :users, only: [:index, :show, :destroy]
  end
  resources :categories, only: [:index, :show] do
    resources :lessons, only: :show
  end
  resources :lessons, only: [:create, :update]
  resources :users
  resources :relationships, only: [:create, :destroy]
  resources :activities
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many :results, dependent: :destroy
  has_many :words, through: :results

  accepts_nested_attributes_for :results

  enum status: {init: 0, finished: 1, in_progress: 2}

  before_create :init_results

  scope :order_desc, -> {order created_at: :desc}

  def set_score
    score = 0
    results.each do |result|
      if result.answer.present? && result.answer.is_correct?
        score += 1
      end
    end
    assign_attributes score: score
  end

  def init_results
    self.words = category.words.order("RANDOM()").limit(category
      .word_per_lesson)
  end

  def start_lesson
    assign_attributes finish_time: Time.now + category.duration.minutes
    in_progress!
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  load_and_authorize_resource
  before_action :find_category, only: :create

  def create
    @lesson = @category.lessons.new user:current_user
    @lesson.save
    respond_to do |format|
      format.js
    end
  end

  def update
    if @lesson.finished?
      flash[:success] = t "controllers.lessons.lesson_finished_message"
    else
      @lesson.assign_attributes lesson_params
      save_fields
      create_activity current_user.id, @lesson.id
    end
    redirect_to @lesson.category
  end

  def show
    @lesson.start_lesson if @lesson.init?
    @results = @lesson.results
  end

  private
  def lesson_params
    params.require(:lesson).permit :id, results_attributes: [:answer_id, :id]
  end

  def create_activity user_id, target_id
    Activity.create action_type: Activity.types[:finished_lesson],
      user_id: user_id, target_id: target_id
  end
  
  def find_category
    @category = Category.find_by id: params[:lesson][:category_id]
    unless @category
      flash.now[:danger] = t "controllers.lessons.category_not_found"
    end
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper

  def action_button lesson
    case lesson.status
    when "init"
      link_to t("helpers.lessons_helper.button_start"),
        category_lesson_path(lesson.category, lesson),
        class: "btn btn-primary"
    when "finished"
      link_to t("helpers.lessons_helper.button_view"),
        category_lesson_path(lesson.category, lesson),
        class: "btn btn-success"
    else
      link_to t("helpers.lessons_helper.button_continue"),
        category_lesson_path(lesson.category,
          lesson), class: "btn btn-info"
    end
  end

  def status_field lesson
    case lesson.status
    when "init"
      label :status, t("helpers.lessons_helper.status_new"),
        class: "label label-primary"
    when "finished"
      label :status, t("helpers.lessons_helper.status_finished"),
        class: "label label-success"
    else
      label :status, t("helpers.lessons_helper.status_in_progress"),
        class: "label label-info"
    end
  end

  def spent_time_field lesson
    if lesson.spent_time.nil?
      "00:00"
    else
      minutes = (lesson.spent_time/60).to_i
      seconds = lesson.spent_time - minutes*60
      "#{minutes} : #{seconds}"
    end
  end

  def score_field lesson
    if lesson.present? && lesson.finished?
      "#{lesson.score}/#{lesson.category.word_per_lesson}"
    else
      "-/-"
    end
  end

  def correct_answer result, answer
    if result.lesson.finished?
      if answer.is_correct?
        content_tag :span, "", class: "glyphicon glyphicon-ok"
      elsif result.answer == answer && !answer.is_correct?
        content_tag :span, "", class: "glyphicon glyphicon-remove"
      end
    end
  end

  def save_fields
    @lesson.spent_time = @lesson.category.duration * 60 -
      (@lesson.finish_time - Time.now).to_i
    @lesson.set_score
    @lesson.finished!
  end
end

app/views/lessons/_lesson.html.erb
<tr class="lesson-item">
  <td><%= lesson.created_at.to_formatted_s :short %></td>
  <td><%= lesson.category.name %></td>
  <td><%= status_field lesson %></td>
  <td><%= spent_time_field lesson %></td>
  <td><%= score_field lesson %></td>
  <td><%= action_button lesson %></td>
</tr>

app/views/lessons/_result.html.erb
<div class="result-item" xmlns="http://www.w3.org/1999/html">
  <div class="item-header">
    <%= "#{f.index+1}. " %>
    <%= f.object.word.content %>
  </div>
  <div class="item-content">
    <% f.object.word.answers.each_with_index do |answer| %>
      <div>
        <label>
          <% if f.object.lesson.finished? %>
            <%= f.radio_button :answer_id, answer.id, disabled: "disabled" %>
          <% else %>
            <%= f.radio_button :answer_id, answer.id %>
          <% end %>
          <%= answer.content %>
          <%= correct_answer f.object, answer %>
        </label>
      </div>
    <% end %>
  </div>
</div>

app/views/lessons/create.js.erb
<% if @lesson.category.words.count >= @lesson.category.word_per_lesson %>
  $('.lessons-table-header').after('<%= j render "lesson", lesson: @lesson %>');
<% else %>
  alert('Not enough words to create lesson');
<% end %>

app/views/lessons/show.html.erb
<% if current_user.is_admin? %>
  <%= render "layouts/header_admin" %>
<% end %>
<div class="container">
  <%= form_for @lesson do |f| %>
    <div class="lesson-progress-column">
      <% if @lesson.finished? %>
        <div class="score">
          <p><%= t ".score" %></p>
          <span>
            <%= "#{@lesson.score}/#{@lesson.category.word_per_lesson}" %>
          </span>
        </div>
        <div class="btn-result">
          <% if current_user.is_admin? %>
            <%= link_to t("back"), admin_path,
              class: "btn btn-primary btn-back" %>
          <% else %>
            <%= link_to t("back"), @lesson.category,
              class: "btn btn-primary btn-back" %>
          <% end %>
        </div>
      <% else %>
        <div class="sidebar-result">
          <div class="time-remaining">
            <p><%= t ".time_remaining" %></p>
            <div id="lesson-countdown"></div>
          </div>
          <div id="lesson-progress">
            <span><%= t ".progress" %></span><br>
            <div class="progressing">
              <span id="number-select">0</span>
              <span><%= "/ #{@lesson.category.word_per_lesson}" %></span>
            </div>
          </div>
          <%= hidden_field :duration, "lesson",
            value: (@lesson.finish_time - Time.now).to_i %>
          <%= f.submit t("button_finish"),
            class: "btn btn-primary finish-lesson" %>
        </div>
      <% end %>
    </div>
    <div class="result-right">
      <div class="result-list">
        <%= f.fields_for :results do |builder| %>
          <%= render "result", f: builder %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>