config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#index"
  get "static_pages/*page", to: "static_pages#show"

  get :admin, to: 'admin/dashboard#index'
  namespace :admin do
    resources :categories
    resources :words, only: [:create, :update, :destroy]
    resources :users, only: [:index, :show, :destroy]
  end
  resources :categories, only: [:index, :show] do
    resources :lessons, only: :show
  end
  resources :lessons, only: [:create, :update]
  resources :users
  resources :relationships, only: [:create, :destroy]
  resources :activities
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :lessons, dependent: :destroy
  has_many :words, dependent: :destroy

  validates :name, presence: true, length: {minimum: 3}
  validates :duration, presence: true, numericality: {only_integer: true}
  validates :word_per_lesson, presence: true, numericality: {only_integer: true}

  scope :ongoing_course, -> (user_id){joins(:lessons).
    where("lessons.user_id = ?", user_id).group("categories.id")}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  load_and_authorize_resource

  before_action :category_supports, only: :show

  def index
    @categories = Category.paginate page: params[:page],
      per_page: Settings.per_page_users
  end

  def new
    @category = Category.new
    render layout: false
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash.now[:success] = t "admin.create_new_category_success_msg"
    end
    respond_to do |format|
      format.js
    end
  end

  def edit
    render layout: false
  end

  def update
    if @category.update_attributes category_params
      flash.now[:success] = t "admin.edit_category_success_message"
    end
    respond_to do |format|
      format.js
    end
  end

  def show
    @word = Word.new
    Settings.mininum_answers_count.times {@word.answers.build}
  end

  def destroy
    @category.destroy
    flash.now[:success] = t "admin.delete_category_success_message"
    respond_to do |format|
      format.js
    end
  end

  private
  def category_params
    params.require(:category).permit :name, :duration, :word_per_lesson
  end

  def category_supports
    @support = Supports::Category_Support.new @category, params
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource

  before_action :find_word, only: :show

  include CategoryUtils

  def index
    @search = Category.search params[:q]
    @categories = @search.result.paginate page: params[:page],
      per_page: Settings.per_page_users
    words_count
  end
  
  def show
    @support = Supports::Category_Support.new @category, params
  end
  
  private
  def find_word
    @words = if params[:search]
      Word.send(params[:filter], current_user.id, params[:id]).
        search(params[:search], params[:id]).send params[:select]
    else
      Word.search "", params[:id]
    end.paginate page: params[:page], per_page: Settings.per_page_users
  end
end

app/views/admin/categories/_category.html.erb
<% if category.present? %>
  <div id="category-item-<%= category.id %>" class="category-item">
    <div class="row category">
      <div class="category-item-content col-md-12">
       <img class="category-img pull-left" src="https://goo.gl/DJ6SNV">
        <div class="category-item-name">
          <%= link_to [:admin, category] do %>
            <h4><strong><%= category.name %></strong></h4>
          <% end %>
          <p class="category-description"></p>
        </div>
      </div>
      <div class="item-footer col-md-12">
        <div class="col-md-9">
          <p><%= t(".duration_title", duration: category.duration) %></p>
          <p><%= t(".label_word_per_lesson", words_per_lesson: category
            .word_per_lesson)
          %></p>
        </div>
        <div class="col-md-3">
          <%= link_to t("button_edit"), edit_admin_category_path(category),
            class: "btn btn-primary", "data-toggle": "modal",
            "data-target": "#category-modal" %>
          <%= link_to t("button_delete"), [:admin, category], method: :delete, data: {
            confirm: t("confirm_delete_message")}, remote: true,
            class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/categories/_edit_form.html.erb
<% provide :modal_header, t(".edit_category_title") %>
<% provide :button_text, t("button_save") %>

<%= render "form" %>

app/views/admin/categories/_form.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">&times;</button>
  <h4 class="modal-title"><%= yield :modal_header %></h4>
</div>
<div>
  <%= form_for [:admin, @category], remote: true do |f| %>
    <div class="modal-body">
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :duration, t("admin.duration_title") %>
      <%= f.text_field :duration, class: "form-control" %>

      <%= f.label :word_per_lesson, t("admin.label_word_per_lesson") %>
      <%= f.text_field :word_per_lesson, class: "form-control" %>
    </div>
    <div class="modal-footer">
      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
      <button class="btn btn-default" data-dismiss="modal">
        <%= t "button_cancel" %>
      </button>
    </div>
  <% end %>
</div>

app/views/admin/categories/_new_form.html.erb
<% provide :modal_header, t(".new_category_title") %>
<% provide :button_text, t("button_create") %>

<%= render "form" %>

app/views/admin/categories/create.js.erb
<% if @category.errors.any? %>
  $("#category-modal .modal-content").html("<%= j render("new_form") %>");
<% else %>
  $("#category-modal").modal("hide");
  $("#category-index-list").prepend(
    "<%= j render("category",category: @category) %>");
  $("#flash-msg").html("<%= j render("shared/flash_message") %>");
<% end %>

app/views/admin/categories/destroy.js.erb
$('#flash-msg').html('<%= j render "shared/flash_message" %>');
$('#category-item-<%= @category.id %>').remove();

app/views/admin/categories/edit.html.erb
<%= render "edit_form" %>

app/views/admin/categories/index.html.erb
<%= render "layouts/header_admin" %>
<div class="container">
  <h1>
    <%= t ".category_index_title" %>
  </h1>
  <%= link_to t(".create_new_category"), new_admin_category_path,
    data: {toggle: "modal", target: "#category-modal"},
    class: "btn btn-primary" %>
  <div id="category-index-list">
    <% if @categories.any? %>
      <% @categories.each do |category| %>
        <%= render "category", category: category %>
      <% end %>
      <%= will_paginate @categories %>
    <% end %>
  </div>

  <div id="category-modal" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/new.html.erb
<%= render "new_form" %>

app/views/admin/categories/show.html.erb
<div class="container admin-category-show">
  <h1><%= t ".words_management" %></h1>
  <div id="div-show-category">
    <div id="div-new-word">
      <%= render "admin/words/word_form", word: @word,
        category_id: @category.id %>
    </div>
    <div id="div-list-word">
      <div id="words-content">
        <% if @support.words.any? %>
          <% @support.words.each do |word| %>
            <%= render "admin/words/word", word: word %>
          <% end %>
          <div class="text-center">
            <%= will_paginate @support.words %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/update.js.erb
<% if @category.errors.any? %>
  $('#category-modal .modal-content').html('<%= j render "edit_form" %>');
<% else %>
  $('#category-modal').modal('hide');
  $('#category-item-<%= @category.id %>').replaceWith(
    '<%= j render "category", category: @category %>');
  $('#flash-msg').html('<%= j render "shared/flash_message" %>');
<% end %>