config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#index"
  get "static_pages/*page", to: "static_pages#show"

  get :admin, to: 'admin/dashboard#index'
  namespace :admin do
    resources :categories
    resources :words, only: [:create, :update, :destroy]
    resources :users, only: [:index, :show, :destroy]
  end
  resources :categories, only: [:index, :show] do
    resources :lessons, only: :show
  end
  resources :lessons, only: [:create, :update]
  resources :users
  resources :relationships, only: [:create, :destroy]
  resources :activities
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :lessons, dependent: :destroy
  has_many :words, dependent: :destroy

  validates :name, presence: true, length: {minimum: 3}
  validates :duration, presence: true, numericality: {only_integer: true}
  validates :word_per_lesson, presence: true, numericality: {only_integer: true}

  scope :ongoing_course, -> (user_id){joins(:lessons).
    where("lessons.user_id = ?", user_id).group("categories.id")}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  load_and_authorize_resource

  before_action :category_supports, only: :show

  def index
    @categories = Category.paginate page: params[:page],
      per_page: Settings.per_page_users
  end

  def new
    @category = Category.new
    render layout: false
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash.now[:success] = t "admin.create_new_category_success_msg"
    end
    respond_to do |format|
      format.js
    end
  end

  def edit
    render layout: false
  end

  def update
    if @category.update_attributes category_params
      flash.now[:success] = t "admin.edit_category_success_message"
    end
    respond_to do |format|
      format.js
    end
  end

  def show
    @word = Word.new
    Settings.mininum_answers_count.times {@word.answers.build}
  end

  def destroy
    @category.destroy
    flash.now[:success] = t "admin.delete_category_success_message"
    respond_to do |format|
      format.js
    end
  end

  private
  def category_params
    params.require(:category).permit :name, :duration, :word_per_lesson
  end

  def category_supports
    @support = Supports::Category_Support.new @category, params
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource

  before_action :find_word, only: :show

  include CategoryUtils

  def index
    @search = Category.search params[:q]
    @categories = @search.result.paginate page: params[:page],
      per_page: Settings.per_page_users
    words_count
  end
  
  def show
    @support = Supports::Category_Support.new @category, params
  end
  
  private
  def find_word
    @words = if params[:search]
      Word.send(params[:filter], current_user.id, params[:id]).
        search(params[:search], params[:id]).send params[:select]
    else
      Word.search "", params[:id]
    end.paginate page: params[:page], per_page: Settings.per_page_users
  end
end

app/views/categories/_category.html.erb
<div class="row category">
  <div class="category-item-content">
    <%= image_tag "https://goo.gl/RGQrxV" %>
  </div>
  <div class="category-item-name">
    <h3><strong><%= category.name %></strong></h3>
  </div>
  <div class="text-right">
    <small>
      <%= "#{@words_count[category.id]} / #{category.words.size}
        #{t(".words_learn")}" %>
    </small>
  </div>
  <div class="progress">
    <div class="progress-bar progress-bar-warning">
      <% if category.words.any? %>
        <%=
          "#{@words_count[category.id]*100/category.words.size}#{t ".percent"}"
        %>
      <% end %>
    </div>
  </div>
  <%= link_to t(".learn_button"), category, class: "btn btn-success" %>
</div>

app/views/categories/_search_form.html.erb
<%= search_form_for @search, class: "input-group" do |f| %>
  <p>
    <%= f.text_field :name_cont, placeholder: t("search") %>
  </p>
  <span class="glyphicon glyphicon-search"></span>
<% end %>

app/views/categories/index.html.erb
<div class="row categories-header">
  <div class="col-md-7 col-md-offset-1">
    <h3>
      <%= link_to t(".link_category"), categories_path, class: "category-head" %>
    </h3>
  </div>
  <div class="col-md-3">
    <%= render "search_form" %>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="categories-content">
        <%= render @categories %>
      </div>
    </div>
    <%= will_paginate @categories %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="container-fluid center parallax">
  <div class="left col-md-offset-2">
    <h1><%= @category.name %></h1>
    <h4><%= t(".label_word_per_lesson", word_per_lesson: @category
      .word_per_lesson) %></h4>
    <h4><%= t(".duration_title", duration: @category.duration) %></h4>
  </div>
</div>

<div class="container-fluid pills-container">
  <ul class="nav nav-tabs col-md-2 col-md-offset-2">
    <li class="active lesson-pill">
      <%= link_to t(".link_lessons"), "#lessons-content",
        data: {toggle: "tab"} %>
    </li>
    <li class="word-pill">
      <%= link_to t(".link_words"), "#word-content",
        data: {toggle: "tab"} %>
    </li>
  </ul>
  <div class="col-md-7" id="category-filter-form">
    <%= render "words/search_form" %>
  </div>
  <div class="container content">
    <div class="tab-content">
      <div id="lessons-content" class="tab-pane fade in active">
        <table class="table table-responsive">
          <tbody>
            <tr class="lessons-table-header">
              <th><%= t ".lessons_table_created_date" %></th>
              <th><%= t ".lessons_table_category" %></th>
              <th><%= t ".lessons_table_status" %></th>
              <th><%= t ".lessons_table_spent_time" %></th>
              <th><%= t ".lessons_table_score" %></th>
              <th>
                <%= form_for @support.lesson, remote: true do |f| %>
                  <%= f.hidden_field :category_id, value: @category.id %>
                  <%= f.submit t("create_lesson"), class: "btn btn-danger" %>
                <% end %>
              </th>
            </tr>

            <div id="div-lesson-list">
              <% if @support.lessons.any? %>
                <% @support.lessons.each do |lesson| %>
                  <%= render "lessons/lesson", lesson: lesson %>
                <% end %>
              <% end %>
            </div>
          </tbody>
        </table>
      </div>
      <div id="word-content">
        <div class="list-words">
          <% if @words.any? %>
            <%= render @words %>
          <% end %>
          <%= will_paginate @words %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/show.js.erb
$('.list-words').html("<%= j render @words %>");